id: "exp2"
description: "I fixed wrong labels in dataset preparation. "
seed: 42
mode: "train"
device: "cuda"
data:
  sample_rate: 32000
  frame_length: 5
  n_mels: 128
  nfft: 2028
  hop_length: 512
  fmax: 16000
  fmin: 20
  top_db: 80
  splitted_datasets:
    birdclefs:
      2024: data/birdclef-2024/train_audio
      2023: data/birdclef-2023/train_audio
      2022: data/birdclef-2022/train_audio
      2021: data/birdclef-2021/train_short_audio 
  short_audio_stategy: "cut_first_10_percent_and_add_to_track"
train:
  fast_dev_run: False
  epoch_number: 20
  batch_size: 148
  num_workers: 10
  timm_model: "efficientnet_b1"
  optimizer: "adam"
  lr: 0.001
  num_classes: 397
  pin_memory: True
  device: "cuda"
  checkpoint_path: "checkpoints/efficientnet_b1/model-epoch=03-val_loss=1.99.ckpt"
  save_model_path: "checkpoints/efficientnet_b1"
  save_model_every_epoch: True
  save_model_every_epoch_path: "./checkpoints/efficientnet_b1/exp2"
  save_model_every_epoch_name: "model_epoch_"
  save_model_every_epoch_overwrite: True
  save_model_every_epoch_keep_last: 20
  float32_matmul_precision: "high"
scheduler:
  gamma: 0.1
  step_size: 1